export const puzzles = {
  S1L1: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","exit","outer","outer","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L2: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","exit","basic","basic","outer",
"outer","outer","outer","basic","outer","basic","outer",
"outer","outer","outer","basic","basic","flask","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L3: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","basic","basic","jet","outer",
"outer","outer","outer","basic","outer","basic","outer",
"outer","exit","basic","basic","basic","flask","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L4: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","key","outer",
"outer","outer","outer","basic","outer","basic","outer",
"outer","outer","outer","flask","basic","basic","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L5: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","exit","outer","jet","basic","basic","outer",
"outer","basic","outer","basic","outer","basic","outer",
"outer","door","basic","key","basic","flask","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L6: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","exit","outer","basic","basic","portal","outer",
"outer","basic","outer","basic","outer","basic","outer",
"outer","portal","basic","basic","basic","flask","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L7: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","portal","outer",
"outer","outer","basic","outer","basic","outer","outer",
"outer","basic","basic","basic","basic","flask","outer",
"outer","basic","outer","outer","outer","basic","outer",
"outer","flask","basic","basic","basic","basic","outer",
"outer","outer","key","outer","basic","outer","outer",
"outer","portal","basic","basic","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L8: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","outer","outer",
"outer","outer","outer","outer","basic","outer","outer",
"outer","basic","basic","basic","basic","flask","outer",
"outer","basic","basic","outer","outer","basic","outer",
"outer","flask","basic","basic","basic","basic","outer",
"outer","outer","key","outer","jet","basic","outer",
"outer","outer","basic","basic","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L9: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","basic","basic","portal","outer",
"outer","outer","outer","basic","outer","jet","outer",
"outer","jet","basic","basic","basic","flask","outer",
"outer","basic","outer","flask","outer","basic","outer",
"outer","flask","basic","basic","basic","basic","outer",
"outer","basic","outer","flask","outer","basic","outer",
"outer","portal","basic","basic","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S1L10: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","flask","basic","portal","outer",
"outer","outer","outer","basic","outer","basic","outer",
"outer","flask","basic","jet","basic","flask","outer",
"outer","basic","outer","flask","outer","basic","outer",
"outer","key","basic","door","basic","portal","outer",
"outer","basic","outer","basic","outer","basic","outer",
"outer","portal","basic","portal","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L1: ["outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","3","basic","2","outer",
"outer","exit","basic","basic","outer","basic","outer",
"outer","outer","outer","flask","basic","1","outer",
"outer","outer","outer","basic","outer","outer","outer",
"outer","outer","outer","start","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L2: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","portal","outer",
"outer","outer","outer","flask","outer","1","outer",
"outer","3","basic","basic","basic","basic","outer",
"outer","basic","basic","outer","basic","2","outer",
"outer","basic","basic","basic","basic","basic","outer",
"outer","outer","key","basic","basic","outer","outer",
"outer","outer","basic","portal","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L3: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","basic","outer",
"outer","outer","outer","basic","outer","3","outer",
"outer","1","basic","basic","basic","flask","outer",
"outer","basic","basic","outer","basic","2","outer",
"outer","jet","basic","basic","basic","flask","outer",
"outer","outer","flask","basic","jet","outer","outer",
"outer","outer","basic","key","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L4: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","portal","outer",
"outer","outer","outer","basic","outer","2","outer",
"outer","3","basic","flask","basic","flask","outer",
"outer","basic","basic","outer","basic","1","outer",
"outer","basic","basic","flask","basic","basic","outer",
"outer","outer","key","outer","basic","outer","outer",
"outer","outer","basic","portal","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L5: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","portal","outer",
"outer","outer","outer","flask","outer","3","outer",
"outer","2","basic","basic","basic","flask","outer",
"outer","basic","basic","outer","basic","1","outer",
"outer","jet","basic","basic","basic","basic","outer",
"outer","outer","key","outer","jet","outer","outer",
"outer","outer","basic","portal","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L6: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","basic","portal","outer",
"outer","outer","outer","basic","outer","2","outer",
"outer","1","basic","basic","basic","flask","outer",
"outer","basic","flask","outer","flask","3","outer",
"outer","jet","basic","basic","basic","basic","outer",
"outer","outer","key","basic","jet","outer","outer",
"outer","outer","basic","portal","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
S2L7: ["outer","outer","outer","outer","outer","outer","outer",
"outer","exit","basic","door","portal","portal","outer",
"outer","outer","outer","basic","outer","1","outer",
"outer","2","basic","flask","basic","basic","outer",
"outer","basic","basic","outer","basic","3","outer",
"outer","jet","basic","basic","basic","flask","outer",
"outer","outer","key","basic","flask","outer","outer",
"outer","outer","portal","portal","basic","start","outer",
"outer","outer","outer","outer","outer","outer","outer",
],
};
