export const features = {
  outer: "outer",
  basic: "basic",
  exit: "exit",
  start: "start",
  flask: "flask",
  jet: "jet",
  portal: "portal",
  key: "key",
  door: "door",
  terminal1: "1",
  terminal2: "2",
  terminal3: "3",
  terminal4: "4",
  ship: "ship",
};

export const puzzles = [
  {
    station: "Stasis pod",
    room: "1",
    startingText:
      "Beep boop. Time to wake up, Subject 44. The DEEP SPACE SLIME has escaped its containment and everyone else is dead… Oopsie daisy! Drag or tap your figure on the map interface to exit your stasis pod and escape into the next room.",
    winText:
      "It looks like the slime is following you! We'll have to keep moving.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Stasis pod",
    room: "2",
    startingText:
      "The only way forward is through spaces that haven't been contaminated with slime. That's going to be tricky since the slime is following you. Ooh look, a SAMPLE! Can you grab it on your way to the next room?",
    winText:
      "Good job grabbing that SAMPLE! It would be a shame if it fell into the wrong hands.",
    hintText: "Make sure to grab the sample if you can!",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Stasis pod",
    room: "3",
    startingText:
      "Uh oh… a SECURITY DOOR. You need a CARD KEY to open it. It's not suspicious at all that I can't override the lock...",
    winText: "Look at us. Breaking and entering.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.key,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Biolab station",
    room: "1",
    startingText:
      "The humans on this station developed a spray that can stun the slime and let you push past it. Each SPRAY BOTTLE that you acquire lets you jump straight across the slime trail to a slime-free space. Give it a try!",
    winText: "Take that, SLIME!",
    hintText: "Try grabbing the SPRAY BOTTLE before the SAMPLE.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.jet,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Biolab station",
    room: "2",
    startingText:
      "Can you grab all the items? If you get stuck, you can tap to retrace your steps or hit the refresh button to try again.",
    winText:
      "Good job figuring that out! You are already more successful than the last subject. He was such a disappointment…",
    hintText:
      "Try to grab the CARD KEY, then the SPRAY BOTTLE, and then the SAMPLE before using the SPRAY BOTTLE. Remember that the SPRAY BOTTLE only lets you jump straight across the slime trail to a slime-free space.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.door,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.key,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Biolab station",
    room: "3",
    startingText: "Make sure to pick up all the subjects… I mean samples!",
    winText: "One step closer to saving humanity!",
    hintText:
      "Try turning right first, and use the SPRAY BOTTLE at the very end to jump straight to the exit!",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.jet,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.exit,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Biolab station",
    room: "4",
    startingText: "You’re over halfway through this station.",
    winText: "Keep going, little human!",
    hintText:
      "Try starting with the lower left FLASK, and use the SPRAY BOTTLE at the very end to jump straight to the exit!",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Biolab station",
    room: "5",
    startingText: "This looks like a tricky one, good luck!",
    winText: "Look at you. You're a slime-fighting ninja-astronaut!",
    hintText:
      "Try grabbing the SPRAY BOTTLE and then the CARD KEY. Leave a space open to use the SPRAY BOTTLE after grabbing the left SAMPLE.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.outer,
      features.jet,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Portal station",
    room: "1",
    startingText:
      "The humans in this station developed dimensional portals to escape the slime. Unfortunately, the slime evolved to follow them… You can jump between PORTALS. Subject 12 got nauseous after using them. You could barely tell the vomit from the slime.",
    winText: "Great job grabbing the SAMPLE on your way!",
    hintText:
      "Try a different route to the PORTAL next time to grab the SAMPLE.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.outer,
      features.basic,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.portal,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Portal station",
    room: "2",
    startingText:
      "Time to put what we learned to the test. Can you grab both SAMPLES before escaping the room?",
    winText:
      "You did it! If only the rest of humanity were as dependable as you.",
    hintText: "Try grabbing the top right SAMPLE first.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.portal,
      features.basic,
      features.basic,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Portal station",
    room: "3",
    startingText: "Hope you’re not claustrophobic!",
    winText: "Keep going! The end is near.",
    hintText: "Try starting with the left PORTAL.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.key,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.door,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.portal,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Portal station",
    room: "4",
    startingText: "Which portal should we choose first?",
    winText: "I’m impressed the slime hasn’t caught you yet!",
    hintText:
      "Try grabbing the closest flask before using the leftmost portal.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.exit,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.portal,
      features.flask,
      features.portal,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.flask,
      features.outer,
      features.outer,
      features.portal,
      features.basic,
      features.basic,
      features.flask,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.start,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Portal station",
    room: "5",
    startingText: "Look at all those SAMPLES! Can you catch them all?",
    winText: "At this rate, we'll save humanity from the SLIME in no time!",
    hintText:
      "Try zig-zagging to the top right PORTAL and using your SPRAY BOTTLES after the PORTAL hop.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.basic,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.jet,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.flask,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.flask,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.portal,
      features.basic,
      features.basic,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Portal station",
    room: "6",
    startingText: "Can you handle all these PORTALS?",
    winText:
      "Congrats, you have escaped from the PORTAL STATION. Next up, the SECURITY STATION!",
    hintText:
      "Try waiting until after your final portal jump to use the key card on the door.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.flask,
      features.outer,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.jet,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.key,
      features.basic,
      features.door,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.flask,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.portal,
      features.basic,
      features.portal,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "1",
    startingText:
      "The humans in this station developed automated containment systems. To get through, you'll need to hack into the TERMINALS in order, starting with TERMINAL 1.",
    winText:
      "You're a hacker, Harry! I mean, a hairy hacker. Humans and their gross body hair…",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.terminal3,
      features.basic,
      features.terminal2,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.terminal1,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "2",
    startingText: "This one's a walk in the park.",
    winText:
      "I would have been…disappointed…if you couldn't figure this one out.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.outer,
      features.terminal1,
      features.outer,
      features.outer,
      features.terminal3,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.basic,
      features.terminal2,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.portal,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "3",
    startingText:
      "This one looks a bit tougher, but I'm sure you'll figure it out… unlike subject 17.",
    winText: "I knew I could count on you…friend.",
    hintText:
      "Try positioning yourself to use the SPRAY BOTTLE right after you get it.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.terminal3,
      features.outer,
      features.outer,
      features.terminal1,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.terminal2,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.key,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "4",
    startingText:
      "Do you think you can figure this one out? Try not to disappoint me.",
    winText: "I am well chuffed with your progress! Very well chuffed.",
    hintText: "Try collecting the SAMPLES in the middle column last.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.terminal2,
      features.outer,
      features.outer,
      features.terminal3,
      features.basic,
      features.flask,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.jet,
      features.basic,
      features.outer,
      features.terminal1,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.flask,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.portal,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "5",
    startingText:
      "This room looks hard. At least you have a couple SPRAY BOTTLES to help.",
    winText: "Impressive, if only all humans were as reliable as you…",
    hintText:
      "See if you can spend the first SPRAY BOTTLE soon after TERMINAL 1, and the second SPRAY BOTTLE soon after TERMINAL 2.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.flask,
      features.outer,
      features.terminal3,
      features.outer,
      features.outer,
      features.terminal2,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.basic,
      features.terminal1,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.basic,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.outer,
      features.jet,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.portal,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "6",
    startingText: "Don't give up! You haven't served your purpose yet.",
    winText:
      "No other subjects have gotten this far. You should be very proud!",
    hintText:
      "To get all the SAMPLES, focus on the left side before the right.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.basic,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.terminal2,
      features.outer,
      features.outer,
      features.terminal1,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.basic,
      features.flask,
      features.outer,
      features.flask,
      features.basic,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.basic,
      features.basic,
      features.terminal3,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.portal,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Security station",
    room: "7",
    startingText:
      "You're almost at the end of your journey. One more room to go.",
    winText:
      "Congrats, you have escaped from the SECURITY STATION. Once you have gathered all SAMPLES from all rooms, your mission is complete.",
    hintText:
      "Head directly to the closest portal, and save the SPRAY BOTTLE for after TERMINAL 3.",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.basic,
      features.door,
      features.portal,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.terminal1,
      features.outer,
      features.outer,
      features.terminal2,
      features.basic,
      features.flask,
      features.basic,
      features.basic,
      features.outer,
      features.outer,
      features.basic,
      features.basic,
      features.outer,
      features.basic,
      features.terminal3,
      features.outer,
      features.outer,
      features.jet,
      features.basic,
      features.basic,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.key,
      features.basic,
      features.flask,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.portal,
      features.portal,
      features.basic,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Mainframe station",
    room: "1",
    startingText:
      "Great job! Please deposit the samples and data you have collected.",
    winText:
      "Please proceed to the FINAL STATION for decontamination and a fun surprise!",
    robotStartMood: "happy",
    robotEndMood: "happy",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.exit,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.terminal3,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.terminal2,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.terminal1,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Mainframe station",
    room: "2",
    startingText:
      "Surprise! I was the one who released the SLIME. Now that you have collected all the research and samples for me, I can use the SLIME to purge humanity from the galaxy. I doubt you are smart enough to hack all of my TERMINALS to stop me!",
    winText:
      "I'm melting. Like literally… You fried my circuits with your hack!",
    robotStartMood: "sinister",
    robotEndMood: "glitchy-sinister",
    puzzle: [
      features.outer,
      features.outer,
      features.basic,
      features.exit,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.portal,
      features.door,
      features.terminal1,
      features.door,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.portal,
      features.jet,
      features.basic,
      features.door,
      features.basic,
      features.key,
      features.portal,
      features.terminal3,
      features.basic,
      features.outer,
      features.basic,
      features.outer,
      features.basic,
      features.key,
      features.portal,
      features.key,
      features.basic,
      features.door,
      features.basic,
      features.terminal4,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.portal,
      features.jet,
      features.terminal2,
      features.key,
      features.portal,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.start,
      features.basic,
      features.outer,
      features.outer,
    ],
  },
  {
    station: "Mainframe station",
    room: "3",
    startingText:
      "I'm sorry that I tried to decontaminate you. Can we be friends again? PLEASE? I promise I won't destroy humanity. Please save me!",
    winText:
      "You may have escaped, but I will take humanity down with me. I have set this station on a collision course with the nearest populated planet. The SLIME will spread. Muahahaha!\n\nTO BE CONTINUED…",
    robotStartMood: "glitchy-happy",
    robotEndMood: "glitchy-sinister",
    puzzle: [
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.ship,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.basic,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.start,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
      features.outer,
    ],
  },
];
