name: Lint

on:
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: npm ci

      - name: Prettier
        run: npx prettier -c src/ README.md .github/workflows

      - name: ES lint
        run: npx eslint --ignore-path .gitignore .

      - name: Stylelint
        run: npx stylelint '**/*.css'
